# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'UtilityDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UtilityDemo
  pod 'MBProgressHUD', '~> 1.0.0'
  target 'UtilityDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UtilityDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
